volumes:
  storage:

services:
  api:
    image: docker.studyum.net/likdn
    restart: always
    pull_policy: always
    env_file:
      - ".env"
    ports:
      - "80:8080"
    volumes:
      - ./storage:/storage